### PR TITLE
Improve session start check

### PR DESCRIPTION
**Pull request by npotier**

### CODE REVIEW

**Comment by npotier** [comment]
Hi @mahagr this is a new nice PR. I've taken care of your previous comments, thanks.

**Comment by mahagr** [comment]
Hmm, we only support PHP 5.4+, so maybe there's no point of having fallback to the older code?

**Comment by npotier** [comment]
Ok, is this better ? Thanks.

**Comment by mahagr** [comment]
Yup, much better.

**Comment by flaviocopes** [comment]
What problem does this solve?

**Comment by mahagr** [comment]
From what I can see, it doesn't initialize session if you're in CLI.

**Pull request merged**
